### ISSUE TITLE
binutils-doc installation error on Ubuntu 14.04 after update "binutils-doc binary package" on 2016-05-17 02:09:12 UTC

### ISSUE THREAD

**Issue by undeadgrishnackh** [chef-cookbooks/build-essential#110]
### Cookbook version
[4.0.0]

### Chef-client version
[12.10.24 and 12.10.58 (latest from vagrant omnibus)]

### Platform Details
[ubuntu 14.04]

### Scenario:
[I'm trying to install a PostgresSQL with a recipe. I found an error on the build-essential installation. So I've created a new empty cookbook and recipe to only install build-essential. When i run the cookbook in a vagrant machine with chef-solo I receive an error because chef is trying to install literally from log: 
"==> default: ---- End output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----"

After some search, the problem is that yesterday night Ubuntu has released a new version of this package: https://launchpad.net/ubuntu/trusty/amd64/binutils-doc
the new version is 2.24-5ubuntu14.1. I've tried to manually install in vagrant ssh and it's seem to work, BUT before I need to did a sudo apt-get update:
sudo apt-get update; sudo apt-get -q -y install binutils-doc=2.24-5ubuntu14.1

I've forced my recipe to do this before installing build-essential, but the problem persists because the recipe continue to search the version 2.24-5ubuntu14 instead of 2.24-5ubuntu14.1
]

### Steps to Reproduce:
[default.rb:
------------------
include_recipe 'apt'
execute "apt-get-update-build-essentials" do
  command "apt-get update"
  action :nothing
end

include_recipe 'build-essential::default'
]

### Expected Result:
[the build-essential packages installed correctly]

### Actual Result:
==> default: Starting Chef Client, version 12.10.24
==> default: [2016-05-18T14:47:35+00:00] INFO: *** Chef 12.10.24 ***
==> default: [2016-05-18T14:47:35+00:00] INFO: Platform: x86_64-linux
==> default: [2016-05-18T14:47:35+00:00] INFO: Chef-client pid: 2857
==> default: [2016-05-18T14:47:36+00:00] INFO: Setting the run_list to ["recipe[ServerDEV]"] from CLI options
==> default: [2016-05-18T14:47:36+00:00] INFO: Run List is [recipe[ServerDEV]]
==> default: [2016-05-18T14:47:36+00:00] INFO: Run List expands to [ServerDEV]
==> default: [2016-05-18T14:47:36+00:00] INFO: Starting Chef Run for vagrant-5da34ceb
==> default: [2016-05-18T14:47:36+00:00] INFO: Running start handlers
==> default: [2016-05-18T14:47:36+00:00] INFO: Start handlers complete.
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: [2016-05-18T14:47:37+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
==> default: [2016-05-18T14:47:37+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
==> default: Recipe: build-essential::_debian
==> default:   
==> default: * apt_package[autoconf] action install
==> default: [2016-05-18T14:47:40+00:00] INFO: apt_package[autoconf] installed autoconf at 2.69-6
==> default: 
==> default:     - install version 2.69-6 of package autoconf
==> default:   * apt_package[binutils-doc] action install
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `install` on resource 'apt_package[binutils-doc]'
==> default:     
==> default: ================================================================================
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:     
==> default: ------------------------------------
==> default:     
==> default: Expected process to exit with [0], but received '100'
==> default: 
==> default:     
==> default: ---- Begin output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: 
==> default:     
==> default: STDOUT: Reading package lists...
==> default: 
==> default:     
==> default: Building dependency tree...
==> default: 
==> default:     
==> default: Reading state information...
==> default: 
==> default:     
==> default: The following packages were automatically installed and are no longer required:
==> default: 
==> default:     
==> default:   chef-zero erubis ohai ruby-diff-lcs ruby-erubis ruby-hashie ruby-highline
==> default: 
==> default:     
==> default:   ruby-ipaddress ruby-mime-types ruby-mixlib-authentication ruby-mixlib-cli
==> default: 
==> default:     
==> default:   ruby-mixlib-config ruby-mixlib-log ruby-mixlib-shellout ruby-net-ssh
==> default: 
==> default:     
==> default:   ruby-net-ssh-gateway ruby-net-ssh-multi ruby-rack ruby-rest-client
==> default: 
==> default:     
==> default:   ruby-sigar ruby-systemu ruby-yajl
==> default: 
==> default:     
==> default: Use 'apt-get autoremove' to remove them.
==> default: 
==> default:     
==> default: The following NEW packages will be installed:
==> default: 
==> default:     
==> default:   binutils-doc
==> default: 
==> default:     
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: 
==> default:     
==> default: Need to get 574 kB of archives.
==> default: 
==> default:     
==> default: After this operation, 645 kB of additional disk space will be used.
==> default: 
==> default:     
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main binutils-doc all 2.24-5ubuntu14
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.88.149 80]
==> default: 
==> default:     
==> default: STDERR: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-doc_2.24-5ubuntu14_all.deb  404  Not Found [IP: 91.189.88.149 80]
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: 
==> default:     
==> default: ---- End output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: 
==> default:     
==> default: Ran apt-get -q -y install binutils-doc=2.24-5ubuntu14 returned 100
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Cookbook Trace:
==> default:     
==> default: ---------------
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:114:in `block in method_missing'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:113:in `each'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:113:in `method_missing'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/_debian.rb:22:in `block in from_file'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:104:in `instance_eval'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:104:in `evaluate'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:47:in `potentially_at_compile_time'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/_debian.rb:20:in `from_file'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/ServerDEV/recipes/default.rb:14:in `from_file'
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Resource Declaration:
==> default:     
==> default: ---------------------
==> default:     
==> default: # In /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: 108:         resource = @recipe.send(m, *args, &block)
==> default: 
==> default:     
==> default: 109:         if resource.is_a?(Chef::Resource)
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Compiled Resource:
==> default:     
==> default: ------------------
==> default:     
==> default: # Declared in /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:108:in `method_missing'
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: apt_package("binutils-doc") do
==> default: 
==> default:     
==> default:   package_name "binutils-doc"
==> default: 
==> default:     
==> default:   action [:nothing]
==> default: 
==> default:     
==> default:   retries 0
==> default: 
==> default:     
==> default:   retry_delay 2
==> default: 
==> default:     
==> default:   default_guard_interpreter :default
==> default: 
==> default:     
==> default:   declared_type :package
==> default: 
==> default:     
==> default:   cookbook_name :"build-essential"
==> default: 
==> default:     
==> default:   recipe_name "_debian"
==> default: 
==> default:     
==> default: end
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Platform:
==> default:     
==> default: ---------
==> default:     
==> default: x86_64-linux
==> default:     
==> default: 
==> default: 
==> default:   
==> default: 
==> default:   
==> default: ================================================================================
==> default:   
==> default: Recipe Compile Error in /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/ServerDEV/recipes/default.rb
==> default:   
==> default: ================================================================================
==> default:   
==> default: 
==> default: 
==> default:   
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:   
==> default: ------------------------------------
==> default:   
==> default: apt_package[binutils-doc] (build-essential::_debian line 108) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: 
==> default:   
==> default: ---- Begin output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: 
==> default:   
==> default: STDOUT: Reading package lists...
==> default: 
==> default:   
==> default: Building dependency tree...
==> default: 
==> default:   
==> default: Reading state information...
==> default: 
==> default:   
==> default: The following packages were automatically installed and are no longer required:
==> default: 
==> default:   
==> default:   chef-zero erubis ohai ruby-diff-lcs ruby-erubis ruby-hashie ruby-highline
==> default: 
==> default:   
==> default:   ruby-ipaddress ruby-mime-types ruby-mixlib-authentication ruby-mixlib-cli
==> default: 
==> default:   
==> default:   ruby-mixlib-config ruby-mixlib-log ruby-mixlib-shellout ruby-net-ssh
==> default: 
==> default:   
==> default:   ruby-net-ssh-gateway ruby-net-ssh-multi ruby-rack ruby-rest-client
==> default: 
==> default:   
==> default:   ruby-sigar ruby-systemu ruby-yajl
==> default: 
==> default:   
==> default: Use 'apt-get autoremove' to remove them.
==> default: 
==> default:   
==> default: The following NEW packages will be installed:
==> default: 
==> default:   
==> default:   binutils-doc
==> default: 
==> default:   
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: 
==> default:   
==> default: Need to get 574 kB of archives.
==> default: 
==> default:   
==> default: After this operation, 645 kB of additional disk space will be used.
==> default: 
==> default:   
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main binutils-doc all 2.24-5ubuntu14
==> default: 
==> default:   
==> default:   404  Not Found [IP: 91.189.88.149 80]
==> default: 
==> default:   
==> default: STDERR: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-doc_2.24-5ubuntu14_all.deb  404  Not Found [IP: 91.189.88.149 80]
==> default: 
==> default:   
==> default: 
==> default: 
==> default:   
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: 
==> default:   
==> default: ---- End output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: 
==> default:   
==> default: Ran apt-get -q -y install binutils-doc=2.24-5ubuntu14 returned 100
==> default:   
==> default: 
==> default: 
==> default:   
==> default: Cookbook Trace:
==> default:   
==> default: ---------------
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:114:in `block in method_missing'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:113:in `each'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:113:in `method_missing'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/_debian.rb:22:in `block in from_file'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:104:in `instance_eval'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:104:in `evaluate'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:47:in `potentially_at_compile_time'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/_debian.rb:20:in `from_file'
==> default: 
==> default:   
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> default: 
==> default:     /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/ServerDEV/recipes/default.rb:14:in `from_file'
==> default:   
==> default:   Relevant File Content:
==> default:   ----------------------
==> default:   /tmp/vagrant-chef/cc7dd3aa94711bf56b33353c4edcde71/cookbooks/build-essential/libraries/timing.rb:
==> default:   
==> default:   107:        def method_missing(m, *args, &block)
==> default:   108:          resource = @recipe.send(m, *args, &block)
==> default:   109:          if resource.is_a?(Chef::Resource)
==> default:   110:            actions = Array(resource.action)
==> default:   111:            resource.action(:nothing)
==> default:   112:  
==> default:   113:            actions.each do |action|
==> default:   114>>             resource.run_action(action)
==> default:   115:            end
==> default:   116:          end
==> default:   117:          resource
==> default:   118:        end
==> default:   119:      end
==> default:   120:    end
==> default:   121:  end
==> default:   122:  
==> default:   123:  # Include the timing module into the main recipe DSL
==> default:   
==> default:   Platform:
==> default:   ---------
==> default:   x86_64-linux
==> default:   
==> default:   
==> default:   Running handlers:
==> default: [2016-05-18T14:47:41+00:00] ERROR: Running exception handlers
==> default:   Running handlers complete
==> default: [2016-05-18T14:47:41+00:00] ERROR: Exception handlers complete
==> default:   Chef Client failed. 1 resources updated in 05 seconds
==> default: [2016-05-18T14:47:41+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-05-18T14:47:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-05-18T14:47:41+00:00] ERROR: apt_package[binutils-doc] (build-essential::_debian line 108) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following packages were automatically installed and are no longer required:
==> default:   chef-zero erubis ohai ruby-diff-lcs ruby-erubis ruby-hashie ruby-highline
==> default:   ruby-ipaddress ruby-mime-types ruby-mixlib-authentication ruby-mixlib-cli
==> default:   ruby-mixlib-config ruby-mixlib-log ruby-mixlib-shellout ruby-net-ssh
==> default:   ruby-net-ssh-gateway ruby-net-ssh-multi ruby-rack ruby-rest-client
==> default:   ruby-sigar ruby-systemu ruby-yajl
==> default: Use 'apt-get autoremove' to remove them.
==> default: The following NEW packages will be installed:
==> default:   binutils-doc
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 574 kB of archives.
==> default: After this operation, 645 kB of additional disk space will be used.
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main binutils-doc all 2.24-5ubuntu14
==> default:   404  Not Found [IP: 91.189.88.149 80]
==> default: STDERR: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-doc_2.24-5ubuntu14_all.deb  404  Not Found [IP: 91.189.88.149 80]
==> default: 
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: ---- End output of apt-get -q -y install binutils-doc=2.24-5ubuntu14 ----
==> default: Ran apt-get -q -y install binutils-doc=2.24-5ubuntu14 returned 100
==> default: [2016-05-18T14:47:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
Creation Error! Vagrant UP ABORT!

**Comment by spiderbites** [comment]
Did you figure out any workaround for this?  I'm having the same issue.

**Comment by mcliment** [comment]
The thing is that the Ubuntu 14.04 image contains outdated package lists and some of them are no longer available.
As a workaround I did the following:
`> vagrant ssh` or `> kitchen login` if using Kitchen
Then at the command line jsut:
`> sudo apt-get update` to update the repository indexes
Finally exit the SSH session and try to run Vagrant/Kitchen again as usual.

**Comment by spiderbites** [comment]
Thanks, I ended up just updating my Ubuntu image.

**Comment by undeadgrishnackh** [comment]
@mcliment  I've tried to do this both in vagrant ssh and kitchen login, but the issue remains also after the update. The chef recipe try to get always the old package, because the update is with a different name.

@spiderbites sorry for the late reply, I was busy. Yes the workaround I've found is to upgrade the vagrant and kitchen image to ubuntu 15.10 because postgres recipe isn't compliant to ubuntu 15 LTS.

**Comment by tas50** [comment]
You'll need to apply the apt::default cookbook at the beginning of the run or otherwise manually run apt-get update before kicking off chef-client. This is more an issue of how apt manages outdated data. Unfortunately they don't have the logic including in Yum and Zypper where outdated repo data is automatically updated when you try to install packages.  We've debating doing this for you automatically when you try to install packages, but that introduced a whole different set of issues.
