### ISSUE TITLE
Option package_name must be a kind of [String]!  You passed ["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"].

### ISSUE THREAD

**Issue by kirthar** [chef-cookbooks/build-essential#114]
### Cookbook version
Version 6.0.1

### Chef-client version
Chef 12.0.3

### Platform Details
Ubuntu 14.04  in AWS

### Scenario:
I'm trying to run a deploy on an instance with a recipe that uses built-essential.

### Steps to Reproduce:
Run recipe build-essential::default

### Actual Result:
```
Recipe: build-essential::default
  * build_essential[install_packages] action install
    * apt_package[["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"]] action install

      ================================================================================
      Error executing action `install` on resource 'apt_package[["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"]]'
      ================================================================================

      Chef::Exceptions::ValidationFailed
      ----------------------------------
      Option package_name must be a kind of [String]!  You passed ["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"].

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/build-essential/resources/build_essential.rb

       28:     package %w( autoconf binutils-doc bison build-essential flex gettext ncurses-dev )
       29:   when 'fedora', 'rhel'

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/build-essential/resources/build_essential.rb:28:in `block in class_from_file'

      apt_package("["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"]") do
        action :install
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        package_name ["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"]
        timeout 900
        declared_type :package
        cookbook_name "build-essential"
      end


    ================================================================================
    Error executing action `install` on resource 'build_essential[install_packages]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    apt_package[["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"]] (/var/chef/cache/cookbooks/build-essential/resources/build_essential.rb line 28) had an error: Chef::Exceptions::ValidationFailed: Option package_name must be a kind of [String]!  You passed ["autoconf", "binutils-doc", "bison", "build-essential", "flex", "gettext", "ncurses-dev"].

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/build-essential/recipes/default.rb

     22: build_essential 'install_packages' do
     23:   compile_time node['build-essential']['compile_time']
     24: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/build-essential/recipes/default.rb:22:in `from_file'

    build_essential_build_essential("install_packages") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :build_essential
      cookbook_name "build-essential"
      recipe_name "default"
    end
```

**Comment by kirthar** [comment]
Updated server to Chef 12.0.3 and client with `curl -L https://www.opscode.com/chef/install.sh | sudo bash` and fixed.
